language: python
python:
    - "2.7"
install:
    - "pip install Django==1.6"
    - "pip install djangorestframework==2.3.14"
before_script:
    - "pip install python-coveralls coverage"
script:
    - "coverage run runtests.py"
after_success:
    - "coveralls"
notifications:
    email: false

